[tool.poetry]
name = "repl_python3_The-Turing-Test-L5CSY-DJH-4"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
openai = "^0.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
